'use strict';
const ConfigStore=require('./lib/config-store'); const {execFile}=require('child_process'); const {SurfaceDial}=require('./lib/surface-dial'); const bluetooth=require('./lib/bluetooth');
module.exports=ControllerSurfaceDial;
function ControllerSurfaceDial(context){this.context=context;this.commandRouter=context.coreCommand;this.logger=context.logger;this.configManager=context.configManager;this.config=new ConfigStore();this.dial=null;this.buttonDownAt=0;this.clickTimer=null;this.pendingClicks=0;this.longPressFired=false;}
ControllerSurfaceDial.prototype.onVolumioStart=function(){const configFile=this.commandRouter.pluginManager.getConfigurationFile(this.context,'config.json');this.config.loadFile(configFile);return Promise.resolve();};
ControllerSurfaceDial.prototype.onStart=function(){const reconnectMs=Math.max(1000,Number(this.config.get('reconnect_seconds')||5)*1000);this.dial=new SurfaceDial({logger:this.logger,reconnectMs,onRotation:this._onRotation.bind(this),onButton:this._onButton.bind(this)});this.dial.start();this.logger.info('[Surface Dial] Plugin started');return Promise.resolve();};
ControllerSurfaceDial.prototype.onStop=function(){if(this.clickTimer)clearTimeout(this.clickTimer);this.clickTimer=null;this.pendingClicks=0;if(this.dial)this.dial.stop();this.dial=null;this.logger.info('[Surface Dial] Plugin stopped');return Promise.resolve();};
ControllerSurfaceDial.prototype.getConfigurationFiles=function(){return ['config.json'];};
ControllerSurfaceDial.prototype.getUIConfig=function(){const langCode=this.commandRouter.sharedVars.get('language_code');return new Promise((resolve,reject)=>{const request=this.commandRouter.i18nJson(__dirname+'/i18n/strings_'+langCode+'.json',__dirname+'/i18n/strings_en.json',__dirname+'/UIConfig.json');request.then(uiconf=>{const values={device_mac:this.config.get('device_mac')||'',volume_step:Number(this.config.get('volume_step')||2),reverse_rotation:!!this.config.get('reverse_rotation'),manual_haptic:!!this.config.get('manual_haptic'),double_press_ms:Number(this.config.get('double_press_ms')||420),long_press_ms:Number(this.config.get('long_press_ms')||700),reconnect_seconds:Number(this.config.get('reconnect_seconds')||5)};uiconf.sections.forEach(section=>section.content.forEach(item=>{if(Object.prototype.hasOwnProperty.call(values,item.id))item.value=values[item.id];if(['single_press','double_press','long_press'].includes(item.id)){const raw=this.config.get(item.id)||'none';const option=(item.options||[]).find(o=>o.value===raw);if(option)item.value=option;}}));resolve(uiconf);});if(typeof request.fail==='function')request.fail(reject);else if(typeof request.catch==='function')request.catch(reject);});};
ControllerSurfaceDial.prototype.saveSettings=function(data){const getValue=key=>{const v=data[key];return v&&typeof v==='object'&&Object.prototype.hasOwnProperty.call(v,'value')?v.value:v;};const keys=['device_mac','volume_step','reverse_rotation','single_press','double_press','long_press','double_press_ms','long_press_ms','reconnect_seconds','manual_haptic'];keys.forEach(key=>{if(typeof data[key]!=='undefined')this.config.set(key,getValue(key));});if(this.dial)this.dial.setReconnectMs(Math.max(1000,Number(this.config.get('reconnect_seconds')||5)*1000));this.commandRouter.pushToastMessage('success','Surface Dial','Settings saved');return Promise.resolve();};
ControllerSurfaceDial.prototype.scanForDial=function(){this.commandRouter.pushToastMessage('info','Surface Dial','Scanning for Surface Dial… Put the Dial into pairing mode.');return bluetooth.scanForSurfaceDial().then(devices=>{if(!devices.length){this.commandRouter.pushToastMessage('warning','Surface Dial','No Surface Dial found. Hold its pairing button and try again.');return;}const found=devices[0];this.config.set('device_mac',found.mac);this.commandRouter.pushToastMessage('success','Surface Dial','Found '+found.name+' ('+found.mac+'). Re-open settings, then press Pair.');}).catch(err=>{this.commandRouter.pushToastMessage('error','Surface Dial','Scan failed: '+err.message);throw err;});};
ControllerSurfaceDial.prototype.pairDial=function(data){const mac=(data&&data.device_mac)||this.config.get('device_mac');if(!mac){this.commandRouter.pushToastMessage('error','Surface Dial','No Bluetooth address selected. Scan first.');return Promise.resolve();}this.config.set('device_mac',mac);return bluetooth.pair(mac).then(()=>{this.commandRouter.pushToastMessage('success','Surface Dial','Pairing command completed. The Dial should reconnect automatically.');}).catch(err=>{this.commandRouter.pushToastMessage('error','Surface Dial','Pairing failed: '+err.message);throw err;});};
ControllerSurfaceDial.prototype.forgetDial=function(data){const mac=(data&&data.device_mac)||this.config.get('device_mac');if(!mac)return Promise.resolve();return bluetooth.forget(mac).then(()=>{this.config.set('device_mac','');this.commandRouter.pushToastMessage('success','Surface Dial','Surface Dial removed from Bluetooth devices.');}).catch(err=>{this.commandRouter.pushToastMessage('error','Surface Dial','Could not remove device: '+err.message);throw err;});};
ControllerSurfaceDial.prototype._onRotation=function(direction){let dir=direction;if(this.config.get('reverse_rotation'))dir*=-1;const step=Math.min(20,Math.max(1,Number(this.config.get('volume_step')||2)));this._volumioCli(['volume',dir>0?'+'+step:'-'+step]);};
ControllerSurfaceDial.prototype._onButton=function(pressed){const now=Date.now();if(pressed){this.buttonDownAt=now;this.longPressFired=false;return;}const held=now-this.buttonDownAt;const longMs=Math.max(300,Number(this.config.get('long_press_ms')||700));if(held>=longMs){this.longPressFired=true;this.pendingClicks=0;if(this.clickTimer)clearTimeout(this.clickTimer);this.clickTimer=null;this._performAction(this.config.get('long_press')||'previous');return;}this.pendingClicks+=1;const doubleMs=Math.max(200,Number(this.config.get('double_press_ms')||420));if(this.pendingClicks>=2){if(this.clickTimer)clearTimeout(this.clickTimer);this.clickTimer=null;this.pendingClicks=0;this._performAction(this.config.get('double_press')||'next');return;}this.clickTimer=setTimeout(()=>{this.clickTimer=null;if(this.pendingClicks===1)this._performAction(this.config.get('single_press')||'toggle');this.pendingClicks=0;},doubleMs);};
ControllerSurfaceDial.prototype._performAction=function(action){switch(action){case 'toggle':this._volumioCli(['toggle']);break;case 'next':this._volumioCli(['next']);break;case 'previous':this._volumioCli(['previous']);break;case 'none':default:break;}if(this.config.get('manual_haptic')&&this.dial)this.dial.impact(0);};
ControllerSurfaceDial.prototype._volumioCli=function(args){execFile('/usr/local/bin/volumio',args,{timeout:5000},(err,stdout,stderr)=>{if(err)this.logger.error('[Surface Dial] Volumio command failed: '+(stderr||err.message));});};
