'use strict';
const fs=require('fs'); const path=require('path'); const {execFile}=require('child_process');
const SURFACE_DIAL_VENDOR='045E', SURFACE_DIAL_PRODUCT='091B';
class SurfaceDial {
 constructor(options){this.logger=options.logger||console;this.onRotation=options.onRotation||function(){};this.onButton=options.onButton||function(){};this.reconnectMs=options.reconnectMs||5000;this.stepsPerRevolution=options.stepsPerRevolution||50;this.autoHaptic=options.autoHaptic!==false;this.handle=null;this.devicePath=null;this.running=false;this.retryTimer=null;this.lastButtonState=false;}
 start(){if(this.running)return;this.running=true;this._connect();}
 stop(){this.running=false;if(this.retryTimer)clearTimeout(this.retryTimer);this.retryTimer=null;if(this.handle!==null){try{fs.closeSync(this.handle);}catch(e){}}this.handle=null;this.devicePath=null;}
 setReconnectMs(ms){this.reconnectMs=Math.max(1000,Number(ms)||5000);}
 _scheduleReconnect(){if(!this.running||this.retryTimer)return;this.retryTimer=setTimeout(()=>{this.retryTimer=null;this._connect();},this.reconnectMs);}
 _connect(){if(!this.running||this.handle!==null)return;const device=SurfaceDial.findHidrawDevice();if(!device){this._scheduleReconnect();return;}fs.open(device,'r+',(err,fd)=>{if(!this.running){if(!err)fs.close(fd,function(){});return;}if(err){this.logger.warn('[Surface Dial] Cannot open '+device+': '+err.message);this._scheduleReconnect();return;}this.handle=fd;this.devicePath=device;this.logger.info('[Surface Dial] Connected on '+device);this._configureWheel();this._readLoop();});}
 _configureWheel(){if(!this.devicePath)return;const helper=path.join(__dirname,'..','scripts','set-dial-feature.py');execFile('/usr/bin/python3',[helper,this.devicePath,String(this.stepsPerRevolution),this.autoHaptic?'1':'0'],{timeout:3000},(err,stdout,stderr)=>{if(err)this.logger.warn('[Surface Dial] Could not configure 50-step haptics: '+(stderr||err.message));else this.logger.info('[Surface Dial] Configured '+this.stepsPerRevolution+' steps/revolution with automatic haptics '+(this.autoHaptic?'on':'off'));});}
 _disconnect(error){if(error)this.logger.warn('[Surface Dial] Disconnected: '+error.message);if(this.handle!==null){try{fs.closeSync(this.handle);}catch(e){}}this.handle=null;this.devicePath=null;this._scheduleReconnect();}
 _readLoop(){if(!this.running||this.handle===null)return;const buffer=Buffer.alloc(64);fs.read(this.handle,buffer,0,buffer.length,null,(err,bytesRead)=>{if(!this.running)return;if(err||!bytesRead){this._disconnect(err||new Error('empty HID read'));return;}const event=SurfaceDial.parseReport(buffer.subarray(0,bytesRead));if(event){if(typeof event.pressed==='boolean'&&event.pressed!==this.lastButtonState){this.lastButtonState=event.pressed;this.onButton(event.pressed);}if(event.rotation)this.onRotation(event.rotation);}setImmediate(()=>this._readLoop());});}
 impact(repeatCount){if(this.handle===null)return false;const report=Buffer.from([0x01,repeatCount||0x00,0x03,0x00,0x00]);try{fs.writeSync(this.handle,report,0,report.length,null);return true;}catch(e){this.logger.warn('[Surface Dial] Haptic write failed: '+e.message);return false;}}
 static parseReport(bytes){if(!bytes||bytes.length<3||bytes[0]!==0x01)return null;const pressed=(bytes[1]&0x01)===0x01;let rotation=0;if(bytes[2]===0x01)rotation=1;else if(bytes[2]===0xff)rotation=-1;return {pressed,rotation};}
 static findHidrawDevice(){const base='/sys/class/hidraw';let entries;try{entries=fs.readdirSync(base);}catch(e){return null;}for(const entry of entries){const uevent=path.join(base,entry,'device','uevent');let text='';try{text=fs.readFileSync(uevent,'utf8').toUpperCase();}catch(e){continue;}const idMatch=text.includes('0000045E:0000091B')||(text.includes('045E')&&text.includes('091B'));if(idMatch)return '/dev/'+entry;}return null;}
}
module.exports={SurfaceDial,SURFACE_DIAL_VENDOR,SURFACE_DIAL_PRODUCT};
